### ISSUE TITLE
we cant unlock star powers and gadgets

### ISSUE THREAD

**Issue by ghost** [chainsawy/RoyaleBrawl#16]
we cant unlock star powers and gadgets
and we cant get all brawlers
and also there is no battle end screen, it remains forever like this.
Fix it pls.

**Comment by xmooncoodex** [comment]
Ты долбаеб? Бравлеров? Ты долбаеб? Так блять открывай бравл пасс и трофейную дорогу. Какого там Энда нету? Батла? Иди блять делай LogicAcessory, а хотя, ты же негр.. Тогда пошёл нахуй!
