### ISSUE TITLE
dickdev suck suck suck

### ISSUE THREAD

**Issue by SavokBS** [chainsawy/RoyaleBrawl#2]
🙃

**Comment by xeondev1337** [comment]
++++++++++++++++++++++

**Comment by SavokBS** [comment]
🙃

**Comment by KittenPro** [comment]
рояль +- норм

**Comment by SavokBS** [comment]
🦼

**Comment by xeondev1337** [comment]
> рояль +- норм

чел) чем он норм когда сам нихуя не может сделать и только пользовался тем что я ему какое то время помогал
